return {
	"glepnir/dashboard-nvim", -- dashboard on start
	event = "VimEnter",
	config = function()
		require("dashboard").setup({
			theme = "doom",
			config = {
				header = {
					"",
					"",
					"",
					"███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗",
					"████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║",
					"██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║",
					"██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║",
					"██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║",
					"╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝",
					"",
					"",
					"",
				},
				center = {
					{
						icon = "󰙅 ",
						icon_hl = "Title",
						desc = "Explore files",
						desc_hl = "String",
						key = "e",
						keymap = "SPC e",
						key_hl = "Number",
						action = ":Neotree float",
					},
					{
						icon = "󰈞 ",
						icon_hl = "Title",
						desc = "Find files",
						desc_hl = "String",
						key = "f",
						keymap = "SPC f f",
						key_hl = "Number",
						action = ":Telescope find_files",
					},
					{
						icon = "󱋡 ",
						icon_hl = "Title",
						desc = "Recent files",
						desc_hl = "String",
						key = "r",
						keymap = "SPC f r",
						key_hl = "Number",
						action = ":Telescope oldfiles",
					},
					{
						icon = " ",
						icon_hl = "Title",
						desc = "Find word",
						desc_hl = "String",
						key = "w",
						keymap = "SPC f w",
						key_hl = "Number",
						action = ":Telescope live_grep",
					},
					{
						icon = " ",
						icon_hl = "Title",
						desc = "Git branches",
						desc_hl = "String",
						key = "b",
						keymap = "SPC g b",
						key_hl = "Number",
						action = ":Telescope git_branches",
					},
					{
						icon = "󰁯 ",
						icon_hl = "Title",
						desc = "Restore session",
						desc_hl = "String",
						key = "s",
						keymap = "SPC w r",
						key_hl = "Number",
						action = ":SessionRestore",
					},
					{
						icon = " ",
						icon_hl = "Title",
						desc = "Quit NVim",
						desc_hl = "String",
						key = "q",
						keymap = "SPC q",
						key_hl = "Number",
						action = ":q",
					},
				},
			},
		})
	end,
	dependencies = { "nvim-tree/nvim-web-devicons" },
}
